import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { Suspense } from 'react';
import LoadingPage from '@/app/loading';

const InterFont = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Bob’s car dealer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${InterFont.variable} antialiased tw-min-h-[100vh] tw-min-w-[100%] tw-pb-20`}>
        <Header />
          <main className="tw-flex tw-w-full tw-flex-col tw-items-stretch tw-justify-center">
            <Suspense fallback={<LoadingPage />}>
            { children }
            </Suspense>
          </main>
      </body>
    </html>
  );
}
